version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: dockerfile
    image: laravel-app:11.47.0
    container_name: laravel_app
    working_dir: /var/www/html
    volumes:
      - ./app:/var/www/html
    ports:
      - "8000:80"
    environment:
      APP_ENV: local
      APP_DEBUG: "1"
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: laravel
      DB_USERNAME: laravel
      DB_PASSWORD: secret
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: laravel_db
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata:
